version: '2'
services:
    generator-app:
        image: generator
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://generator-postgresql:5432/generator
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    generator-postgresql:
        extends:
            file: postgresql.yml
            service: generator-postgresql
